[build]
  command = "bash ./build.sh && ng build --prod && npm run scully"
  publish = "dist/static"

[template.environment]
  MY_API_KEY="YOUR FLOTIQ API KEY"
  SNIPCART_API_KEY="YOUR SNIPCART PUBLIC API KEY"
