export interface MediaWithoutInternal {
    /**
     * Unique ID of the object, must be generated by the user
     */
    id: string;
    url: string;
    size: number;
    type: string;
    width?: number;
    height?: number;
    source: string;
    fileName: string;
    mimeType: string;
    extension: string;
    externalId?: string;
}
