import { DataSource } from './dataSource';
export interface ProductWithoutInternal {
    /**
     * Unique ID of the object, must be generated by the user
     */
    id: string;
    name: string;
    slug: string;
    price: number;
    description?: string;
    productImage?: Array<DataSource>;
    productGallery?: Array<DataSource>;
}
